name: migration-prod
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Migration action'
        required: true
        default: 'run'
        type: choice
        options:
          - run
          - revert

jobs:
  migration-prod:
    runs-on: [self-hosted, production]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_HASH_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_HASH_PAT }}

      - name: Checkout Compose Repo
        uses: actions/checkout@v4
        with:
          repository: meogle-share/blog-infra
          ref: main
          path: blog-infra
          token: ${{ secrets.GIT_HUB_HASH_PAT }}

      - name: Run Migration
        if: ${{ inputs.action == 'run' }}
        working-directory: blog-infra
        env:
          MEOGLE_PG_DATABASE: ${{ secrets.MEOGLE_PROD_PG_DATABASE }}
          MEOGLE_PG_USERNAME: ${{ secrets.MEOGLE_PROD_PG_USERNAME }}
          MEOGLE_PG_PASSWORD: ${{ secrets.MEOGLE_PROD_PG_PASSWORD }}
          MEOGLE_JWT_SECRET: ${{ secrets.MEOGLE_JWT_SECRET }}
        run: |
          docker compose -p meogle -f docker-compose.yml -f docker-compose.prod.yml run --rm was npm run migration:run:prod

      - name: Revert Migration
        if: ${{ inputs.action == 'revert' }}
        working-directory: blog-infra
        env:
          MEOGLE_PG_DATABASE: ${{ secrets.MEOGLE_PROD_PG_DATABASE }}
          MEOGLE_PG_USERNAME: ${{ secrets.MEOGLE_PROD_PG_USERNAME }}
          MEOGLE_PG_PASSWORD: ${{ secrets.MEOGLE_PROD_PG_PASSWORD }}
          MEOGLE_JWT_SECRET: ${{ secrets.MEOGLE_JWT_SECRET }}
        run: |
          docker compose -p meogle -f docker-compose.yml -f docker-compose.prod.yml run --rm was npm run migration:revert:prod